In [1]:
lst = [1,2,3,4,5]

In [2]:
import numpy as np

In [3]:
np.array(lst)

array([1, 2, 3, 4, 5])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(2)

array([1., 1.])

In [12]:
np.linspace(0,5,9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.

In [13]:
np.linspace(0,4,10)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Python’s function NumPy eye () is one of the in-built functions which is used in order to return a resultant matrix i.e., a two-dimensional array having the value of 1 in the diagonal section in the matrix and 0 placed at values in all other elements in the matrix (elsewhere with respect to the specific position on the kth value).

In [15]:
np.random.rand(7)

array([0.55189241, 0.91378421, 0.58531166, 0.82836214, 0.06883123,
       0.47882582, 0.42968293])

In [16]:
np.random.rand(3,4)

array([[0.24194155, 0.10724643, 0.11961908, 0.80361948],
       [0.54171628, 0.24548804, 0.29493888, 0.1214685 ],
       [0.50907663, 0.04696899, 0.44049777, 0.72989306]])

In [17]:
np.random.randn(3)

array([-0.85118717, -0.65993128,  0.82640691])

In [19]:
np.random.randn(4,2)

array([[ 0.3426817 , -1.20329726],
       [-0.04172787,  1.16305115],
       [ 0.82172068, -0.72226489],
       [ 0.08168252, -0.59435634]])

In [20]:
np.random.randint(1,100)

24

In [21]:
np.random.randint(1,100,10)

array([ 2, 82, 67, 67,  7, 37, 70, 46, 44, 47])

In [27]:
arr = np.arange(12)

In [29]:
arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
arr.dtype

dtype('int32')

In [36]:
ranarr = np.random.randint(0,40,5)

In [37]:
ranarr

array([ 3, 39,  1,  1, 39])

In [38]:
ranarr.max()

39

In [39]:
ranarr.min()

1

In [41]:
ranarr.mean()

16.6

In [ ]:
arr