In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [8]:
arr[:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_Arr = arr[:6]

In [12]:
slice_of_Arr 

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_Arr[:] = 99

In [14]:
slice_of_Arr

array([99, 99, 99, 99, 99, 99])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy[:] = 100

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

# 2d array indexing

In [23]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d[0][1]

10

In [26]:
arr_2d[1]

array([20, 25, 30])

In [27]:
arr_2d[1,1]

25

In [28]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [29]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [32]:
arr = np.arange(1,11)

In [33]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
bool_arr = arr> 5

In [36]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [38]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])